
version: "3.8"

services:

  mssql_server_db:
    image: mcr.microsoft.com/mssql/server:${MSSQL_SERVER_VERSION}-latest
    user: root
    container_name: mssql_server_db
    restart: unless-stopped
    ports:
      - "1433:1433"
    env_file: .env
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    volumes:
      - ./db-data:/var/opt/mssql/data:rw
    networks:
      - db_network

volumes:
  db-data:

networks:
  db_network:
    driver: bridge