
version: "3.8"

services:

  mysql_db:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql:rw
    networks:
      - db_network

volumes:
  db-data:

networks:
  db_network:
    driver: bridge